# Site settings
title: CSC309
description: "Programming on the Web (Fall 2016)"
author:
  name: Karen Reid
  email: reid@cs.toronto.edu
  github: reidka

# Build settings
exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md'
]

sass:
  sass_dir: static/css/
  style: compressed
